import { Realm } from '@realm/react';

export class User extends Realm.Object {
    id!: number;
    user_code?: string;
    existing_code?: string;
    nationalID?: string;
    name!: string;
    gender?: string;
    dob?: Date;
    date_enrollment?: Date;
    email!: string;
    telephone?: string;
    picture?: string;
    position!: number;
    userstatus!: number;
    cm_id?: string;
    villages_id!: number;
    sectorscontrol?: string;
    highdegree?: string;
    otherdegree?: string;
    highestgrade?: string;
    otherhighestgradenote?: string;
    ifaffiliatedwithsm?: string;
    underwhatcapacity?: string;
    othercapacity?: string;
    ifaffiliatedwithsmasIZU?: string;
    ifaffiliatedwithorg?: string;
    otherorganizationaffilia?: string;
    communityorgrole?: string;
    currentroles?: string;
    hoursforabunzi?: string;
    hoursforchw?: string;
    hoursforizu?: string;
    hoursfornwcr?: string;
    hoursfornycr?: string;
    hoursforvillagelead?: string;
    othergovernmentaffiliass?: string;
    hoursforotherrole?: string;
    workedsetting?: string;
    settingnames?: string;
    yearsecd?: string;
    yearschildcare?: string;
    yearsnursary?: string;
    yearsprimary?: string;
    yearssunday?: string;
    yearscbhs?: string;
    capacityasizu?: string;
    whatorganization?: string;
    settingnamesaee?: string;
    ifreceivetrainingaee?: string;
    whentrainingaee?: string;
    numberofhoursaee?: string;
    howlongwithorgaee?: string;
    howdeliverprogramaee?: string;
    hoursperweekhomevisitaee?: string;
    hoursperweekcommunitygroupaee?: string;
    hoursperweekotheraee?: string;
    othernameprogramaee?: string;
    communitygroupsessionperweekaee?: string;
    homevisitperweekaee?: string;
    timespendperweekaee?: string;
    settingnamesami?: string;
    ifreceivetrainingami?: string;
    whentrainingami?: string;
    numberofhoursami?: string;
    howlongwithorgami?: string;
    howdeliverprogramami?: string;
    hoursperweekhomevisitami?: string;
    homevisitperweekami?: string;
    hoursperweekcommunitygroupami?: string;
    communitygroupsessionperweekami?: string;
    othernameprogramami?: string;
    hoursperweekotherami?: string;
    timespendperweekami?: string;
    settingnamesavega?: string;
    ifreceivetrainingavega?: string;
    whentrainingavega?: string;
    numberofhoursavega?: string;
    howlongwithorgavega?: string;
    howdeliverprogramavega?: string;
    hoursperweekhomevisitavega?: string;
    homevisitperweekavega?: string;
    hoursperweekcommunitygroupavega?: string;
    communitygroupsessionperweekavega?: string;
    othernameprogramavega?: string;
    hoursperweekotheravega?: string;
    timespendperweekavega?: string;
    settingnamesfxb?: string;
    ifreceivetrainingfxb?: string;
    whentrainingfxb?: string;
    numberofhoursfxb?: string;
    howlongwithorgfxb?: string;
    howdeliverprogramfxb?: string;
    hoursperweekhomevisitfxb?: string;
    homevisitperweekfxb?: string;
    hoursperweekcommunitygroupfxb?: string;
    communitygroupsessionperweekfxb?: string;
    othernameprogramfxb?: string;
    hoursperweekotherfxb?: string;
    timespendperweekfxb?: string;
    settingnamesgikuriro?: string;
    ifreceivetraininggikuriro?: string;
    whentraininggikuriro?: string;
    numberofhoursgikuriro?: string;
    howlongwithorggikuriro?: string;
    howdeliverprogramgikuriro?: string;
    hoursperweekhomevisitgikuriro?: string;
    homevisitperweekgikuriro?: string;
    hoursperweekcommunitygroupgikuriro?: string;
    communitygroupsessionperweekgikuriro?: string;
    othernameprogramgikuriro?: string;
    hoursperweekothergikuriro?: string;
    timespendperweekgikuriro?: string;
    settingnamesipa?: string;
    ifreceivetrainingipa?: string;
    whentrainingipa?: string;
    numberofhoursipa?: string;
    howlongwithorgipa?: string;
    howdeliverprogramipa?: string;
    hoursperweekhomevisitipa?: string;
    homevisitperweekipa?: string;
    hoursperweekcommunitygroupipa?: string;
    communitygroupsessionperweekipa?: string;
    othernameprogramipa?: string;
    hoursperweekotheripa?: string;
    timespendperweekipa?: string;
    settingnamesloda?: string;
    ifreceivetrainingloda?: string;
    whentrainingloda?: string;
    numberofhoursloda?: string;
    howlongwithorgloda?: string;
    howdeliverprogramloda?: string;
    hoursperweekhomevisitloda?: string;
    homevisitperweekloda?: string;
    hoursperweekcommunitygrouploda?: string;
    communitygroupsessionperweekloda?: string;
    othernameprogramloda?: string;
    hoursperweekotherloda?: string;
    timespendperweekloda?: string;
    settingnamesminisante?: string;
    ifreceivetrainingminisante?: string;
    whentrainingminisante?: string;
    numberofhoursminisante?: string;
    howlongwithorgminisante?: string;
    howdeliverprogramminisante?: string;
    hoursperweekhomevisitminisante?: string;
    homevisitperweekminisante?: string;
    hoursperweekcommunitygroupminisante?: string;
    communitygroupsessionperweekminisante?: string;
    othernameprogramminisante?: string;
    hoursperweekotherminisante?: string;
    timespendperweekminisante?: string;
    settingnamesncda?: string;
    ifreceivetrainingncda?: string;
    whentrainingncda?: string;
    numberofhoursncda?: string;
    howlongwithorgncda?: string;
    howdeliverprogramncda?: string;
    hoursperweekhomevisitncda?: string;
    homevisitperweekncda?: string;
    hoursperweekcommunitygroupncda?: string;
    communitygroupsessionperweekncda?: string;
    othernameprogramncda?: string;
    hoursperweekotherncda?: string;
    timespendperweekncda?: string;
    settingnamesorora?: string;
    ifreceivetrainingorora?: string;
    whentrainingorora?: string;
    numberofhoursorora?: string;
    howlongwithorgorora?: string;
    howdeliverprogramorora?: string;
    hoursperweekhomevisitorora?: string;
    homevisitperweekorora?: string;
    hoursperweekcommunitygrouporora?: string;
    communitygroupsessionperweekorora?: string;
    othernameprogramorora?: string;
    hoursperweekotherorora?: string;
    timespendperweekorora?: string;
    settingnamesrab?: string;
    ifreceivetrainingrab?: string;
    whentrainingrab?: string;
    numberofhoursrab?: string;
    howlongwithorgrab?: string;
    howdeliverprogramrab?: string;
    hoursperweekhomevisitrab?: string;
    homevisitperweekrab?: string;
    hoursperweekcommunitygrouprab?: string;
    communitygroupsessionperweekrab?: string;
    othernameprogramrab?: string;
    hoursperweekotherrab?: string;
    timespendperweekrab?: string;
    settingnamesuburezi?: string;
    ifreceivetraininguburezi?: string;
    whentraininguburezi?: string;
    numberofhoursuburezi?: string;
    howlongwithorguburezi?: string;
    howdeliverprogramuburezi?: string;
    hoursperweekhomevisituburezi?: string;
    homevisitperweekuburezi?: string;
    hoursperweekcommunitygroupuburezi?: string;
    communitygroupsessionperweekuburezi?: string;
    othernameprogramuburezi?: string;
    hoursperweekotheruburezi?: string;
    timespendperweekuburezi?: string;
    settingnamesworld?: string;
    ifreceivetrainingworld?: string;
    whentrainingworld?: string;
    numberofhoursworld?: string;
    howlongwithorgworld?: string;
    howdeliverprogramworld?: string;
    hoursperweekhomevisitworld?: string;
    homevisitperweekworld?: string;
    hoursperweekcommunitygroupworld?: string;
    communitygroupsessionperweekworld?: string;
    othernameprogramworld?: string;
    hoursperweekotherworld?: string;
    timespendperweekworld?: string;
    settingnamesusaid?: string;
    ifreceivetrainingusaid?: string;
    whentrainingusaid?: string;
    numberofhoursusaid?: string;
    howlongwithorgusaid?: string;
    howdeliverprogramusaid?: string;
    hoursperweekhomevisitusaid?: string;
    homevisitperweekusaid?: string;
    hoursperweekcommunitygroupusaid?: string;
    communitygroupsessionperweekusaid?: string;
    othernameprogramusaid?: string;
    hoursperweekotherusaid?: string;
    timespendperweekusaid?: string;
    otherorganization?: string;
    settingnamesothers?: string;
    ifreceivetrainingothers?: string;
    whentrainingothers?: string;
    numberofhoursothers?: string;
    howlongwithorgothers?: string;
    howdeliverprogramothers?: string;
    hoursperweekhomevisitothers?: string;
    homevisitperweekothers?: string;
    hoursperweekcommunitygroupothers?: string;
    communitygroupsessionperweekothers?: string;
    othernameprogramothers?: string;
    hoursperweekotherothers?: string;
    timespendperweekothers?: string;
    incentives?: string;
    transportincentiveoffen?: string;
    howmuchtransportincentive?: string;
    timeincentiveoffen?: string;
    howmuchtimeincentive?: string;
    otherincentive?: string;
    shirtsize?: string;
    shoesize?: string;
    weekdaysavailability?: string;
    saturdaysavailability?: string;
    sundaysavailability?: string;
    email_verified_at?: Date;
    password!: string;
    remember_token?: string;
    created_at?: Date;
    updated_at?: Date;
    last_seen?: Date;

    static schema = {
        name: 'User',
        primaryKey: 'id',
        properties: {
            id: 'int',
            user_code: 'string?',
            existing_code: 'string?',
            nationalID: 'string?',
            name: 'string',
            gender: 'string?',
            dob: 'date?',
            date_enrollment: 'date?',
            email: 'string',
            telephone: 'string?',
            picture: 'string?',
            position: 'int',
            userstatus: 'int',
            cm_id: 'string?',
            villages_id: 'int',
            sectorscontrol: 'string?',
            highdegree: 'string?',
            otherdegree: 'string?',
            highestgrade: 'string?',
            otherhighestgradenote: 'string?',
            ifaffiliatedwithsm: 'string?',
            underwhatcapacity: 'string?',
            othercapacity: 'string?',
            ifaffiliatedwithsmasIZU: 'string?',
            ifaffiliatedwithorg: 'string?',
            otherorganizationaffilia: 'string?',
            communityorgrole: 'string?',
            currentroles: 'string?',
            hoursforabunzi: 'string?',
            hoursforchw: 'string?',
            hoursforizu: 'string?',
            hoursfornwcr: 'string?',
            hoursfornycr: 'string?',
            hoursforvillagelead: 'string?',
            othergovernmentaffiliass: 'string?',
            hoursforotherrole: 'string?',
            workedsetting: 'string?',
            settingnames: 'string?',
            yearsecd: 'string?',
            yearschildcare: 'string?',
            yearsnursary: 'string?',
            yearsprimary: 'string?',
            yearssunday: 'string?',
            yearscbhs: 'string?',
            capacityasizu: 'string?',
            whatorganization: 'string?',
            settingnamesaee: 'string?',
            ifreceivetrainingaee: 'string?',
            whentrainingaee: 'string?',
            numberofhoursaee: 'string?',
            howlongwithorgaee: 'string?',
            howdeliverprogramaee: 'string?',
            hoursperweekhomevisitaee: 'string?',
            hoursperweekcommunitygroupaee: 'string?',
            hoursperweekotheraee: 'string?',
            othernameprogramaee: 'string?',
            communitygroupsessionperweekaee: 'string?',
            homevisitperweekaee: 'string?',
            timespendperweekaee: 'string?',
            settingnamesami: 'string?',
            ifreceivetrainingami: 'string?',
            whentrainingami: 'string?',
            numberofhoursami: 'string?',
            howlongwithorgami: 'string?',
            howdeliverprogramami: 'string?',
            hoursperweekhomevisitami: 'string?',
            homevisitperweekami: 'string?',
            hoursperweekcommunitygroupami: 'string?',
            communitygroupsessionperweekami: 'string?',
            othernameprogramami: 'string?',
            hoursperweekotherami: 'string?',
            timespendperweekami: 'string?',
            settingnamesavega: 'string?',
            ifreceivetrainingavega: 'string?',
            whentrainingavega: 'string?',
            numberofhoursavega: 'string?',
            howlongwithorgavega: 'string?',
            howdeliverprogramavega: 'string?',
            hoursperweekhomevisitavega: 'string?',
            homevisitperweekavega: 'string?',
            hoursperweekcommunitygroupavega: 'string?',
            communitygroupsessionperweekavega: 'string?',
            othernameprogramavega: 'string?',
            hoursperweekotheravega: 'string?',
            timespendperweekavega: 'string?',
            settingnamesfxb: 'string?',
            ifreceivetrainingfxb: 'string?',
            whentrainingfxb: 'string?',
            numberofhoursfxb: 'string?',
            howlongwithorgfxb: 'string?',
            howdeliverprogramfxb: 'string?',
            hoursperweekhomevisitfxb: 'string?',
            homevisitperweekfxb: 'string?',
            hoursperweekcommunitygroupfxb: 'string?',
            communitygroupsessionperweekfxb: 'string?',
            othernameprogramfxb: 'string?',
            hoursperweekotherfxb: 'string?',
            timespendperweekfxb: 'string?',
            settingnamesgikuriro: 'string?',
            ifreceivetraininggikuriro: 'string?',
            whentraininggikuriro: 'string?',
            numberofhoursgikuriro: 'string?',
            howlongwithorggikuriro: 'string?',
            howdeliverprogramgikuriro: 'string?',
            hoursperweekhomevisitgikuriro: 'string?',
            homevisitperweekgikuriro: 'string?',
            hoursperweekcommunitygroupgikuriro: 'string?',
            communitygroupsessionperweekgikuriro: 'string?',
            othernameprogramgikuriro: 'string?',
            hoursperweekothergikuriro: 'string?',
            timespendperweekgikuriro: 'string?',
            settingnamesipa: 'string?',
            ifreceivetrainingipa: 'string?',
            whentrainingipa: 'string?',
            numberofhoursipa: 'string?',
            howlongwithorgipa: 'string?',
            howdeliverprogramipa: 'string?',
            hoursperweekhomevisitipa: 'string?',
            homevisitperweekipa: 'string?',
            hoursperweekcommunitygroupipa: 'string?',
            communitygroupsessionperweekipa: 'string?',
            othernameprogramipa: 'string?',
            hoursperweekotheripa: 'string?',
            timespendperweekipa: 'string?',
            settingnamesloda: 'string?',
            ifreceivetrainingloda: 'string?',
            whentrainingloda: 'string?',
            numberofhoursloda: 'string?',
            howlongwithorgloda: 'string?',
            howdeliverprogramloda: 'string?',
            hoursperweekhomevisitloda: 'string?',
            homevisitperweekloda: 'string?',
            hoursperweekcommunitygrouploda: 'string?',
            communitygroupsessionperweekloda: 'string?',
            othernameprogramloda: 'string?',
            hoursperweekotherloda: 'string?',
            timespendperweekloda: 'string?',
            settingnamesminisante: 'string?',
            ifreceivetrainingminisante: 'string?',
            whentrainingminisante: 'string?',
            numberofhoursminisante: 'string?',
            howlongwithorgminisante: 'string?',
            howdeliverprogramminisante: 'string?',
            hoursperweekhomevisitminisante: 'string?',
            homevisitperweekminisante: 'string?',
            hoursperweekcommunitygroupminisante: 'string?',
            communitygroupsessionperweekminisante: 'string?',
            othernameprogramminisante: 'string?',
            hoursperweekotherminisante: 'string?',
            timespendperweekminisante: 'string?',
        }
    }
};