export const CREATE_SURVEY_TABLE = `
  CREATE TABLE IF NOT EXISTS Surveys (
    _id TEXT PRIMARY KEY,                 
    id INTEGER NOT NULL,                  
    parent_id INTEGER,                    
    name TEXT NOT NULL, 
    title TEXT NOT NULL,   
    description TEXT,
    status TEXT,
    formDefinition TEXT,
    organization TEXT,
    creator TEXT,
    department TEXT,
    version INTEGER,
    versionHistory TEXT,
    currentVersion TEXT,  
    lastUpdatedBy TEXT,
    settings TEXT,      
    metadata TEXT,
    json TEXT,
    name_kin TEXT,                        
    slug TEXT,                            
    json2 TEXT,           
    json2_bkp TEXT,                       
    survey_status INTEGER,       
    module_id INTEGER,                    
    is_primary INTEGER,     
    table_name TEXT,                      
    post_data TEXT,                       
    fetch_data TEXT,                      
    loads TEXT,                           
    prev_id TEXT,                         
    created_at TEXT,                      
    updated_at TEXT,                      
    order_list INTEGER,          
    project_module_id INTEGER,   
    project_id INTEGER,      
    translations TEXT,                
    source_module_id INTEGER    
  );
`;